### ISSUE TITLE
no handler for route 'auth/oci/config

### ISSUE THREAD

**Issue by eshneken** [hashicorp/vault-plugin-auth-oci#4]
Hello,

I'm following instructions to integrate Vault with my OCI tenancy as described here: https://www.vaultproject.io/docs/auth/oci/

I'm running Vault 1.3.1 and the instructions for the OCI plugin say it is "automatically bundled in Vault releases".

However, when I run this command:

curl --header "X-Vault-Token: $roottoken" --request PUT
--data @hometenancyid.json
http://127.0.0.1:8200/v1/auth/oci/config (127.0.0.1:8200/v1/auth/oci/config)

I get the following error:

{"errors":["no handler for route 'auth/oci/config'"]}

Do I actually need to build and deploy the plugin as opposed to assuming it is already pre-bundled with the vault binaries as the docs specify?

thanks,
Ed

**Comment by kalafut** [comment]
Hi. It is bundled. Did you enable it? (`vault auth enable oci`)

**Comment by eshneken** [comment]
I did not!  I missed that when reading https://www.vaultproject.io/docs/auth/oci/ but did find that in the overview.  Thanks!
